### ISSUE TITLE
❰Bug❱ 💾 - Alex's Mobs Leafcutter anthill TPS hogging

### ISSUE THREAD

**Issue by Higuys153** [Mikaaah/TownsAndKingdoms#100]
**Describe the bug**
<u>A clear and concise description of what the bug is.</u>

►Leafcutter Anthills take massive amounts of TPS

**To Reproduce**
<u>Steps to reproduce the behavior:</u>

1. Find anthill
2. lag

**Expected behavior**
<u>A clear and concise description of what you expected to happen.</u>

1. Find anthill
2. not lag

**Screenshots**
<u>If applicable, add screenshots to help explain your problem.</u>

►
![2024-09-03_18 00 33](https://github.com/user-attachments/assets/0e69cf0c-09e7-422e-938c-6806fe51cb82)
![2024-09-03_18 00 19](https://github.com/user-attachments/assets/76e426d5-0684-45a4-9df3-c283aa5e0155)

**Additional context**
<u>Add any other context about the problem here.</u>

► A fix until Alex's mobs patches this would be to set the spawnrate of the anthills in the default config to 0

**Comment by Mikaaah** [comment]
This is within the 1.18.2 version. This runs a year old version of alexs mobs. The 1.20.1 rework will fix this. Note that you will need to reset your world for the update

**Comment by Higuys153** [comment]
Can you give a rough estimate of what you have to do before the 1.20.1 version is released? (No pressure though 👍)

**Comment by Mikaaah** [comment]
Update releases Friday the 6th.

**Comment by Higuys153** [comment]
What timezone is that?

**Comment by Mikaaah** [comment]
Keep an eye on the discord, Im not certain when on friday it releases.

**Comment by Higuys153** [comment]
I'm just saying that because Friday is usually Thursday for me as I am in AEST
