### ISSUE TITLE
❰Bug❱ 💾 - 

### ISSUE THREAD

**Issue by Ricardo-FR** [Mikaaah/TownsAndKingdoms#101]
**Describe the bug**
<u>A clear and concise description of what the bug is.</u>

►Loading screen freezes

**To Reproduce**
<u>Steps to reproduce the behavior:</u>

►opening the game

**Expected behavior**
<u>A clear and concise description of what you expected to happen.</u>

►for the game to load

**Screenshots**
<u>If applicable, add screenshots to help explain your problem.</u>

►
![Screenshot_1](https://github.com/user-attachments/assets/f4e45abf-f577-45a9-954e-0d6cbc5405b0)

**Additional context**
<u>Add any other context about the problem here.</u>

►So, i was already talking with mika about this, deleting the fancy menu and drippy loading screen didnt help, but it seems that when i created a new profile with the same mods it did allowed me to load, so there is something in the original installation causing trouble, anyways in the new installation created by me i cant join the servers as it gives an error at authentication of username (yes i have an official mojang account) so i dont know if there is some config for joining the server that i also need to port, or if it is another bug.

**Comment by Mikaaah** [comment]
Uhh can you provide the logs?

**Comment by Ricardo-FR** [comment]
Ok, so it seems with the official forge version i can load it up, not sure what was the problem with the other one, but it seems it fixed itself xD...
