### ISSUE TITLE
❰Bug❱ 💾 - 

### ISSUE THREAD

**Issue by SniperUni** [Mikaaah/TownsAndKingdoms#102]
**Describe the bug**
<u>A clear and concise description of what the bug is.</u>

► Non Opped players can Edit skill tree

**To Reproduce**
<u>Steps to reproduce the behavior:</u>

► start world with cheats off

/skilltree editor skilltree:main_tree

**Expected behavior**
<u>A clear and concise description of what you expected to happen.</u>

► non opped players unable to eddit skill tree

**Screenshots**
<u>If applicable, add screenshots to help explain your problem.</u>

►
![image](https://github.com/user-attachments/assets/33e84a83-cf1b-4fd9-a9c0-9fa127a28650)
![image](https://github.com/user-attachments/assets/041705a6-208b-4842-9b9b-e46c62476d5f)

**Additional context**
<u>Add any other context about the problem here.</u>

►

**Comment by Mikaaah** [comment]
Ah alright. Thats odd, ive reported it to the developer of the mod and hopefully will be able to fix it asap

**Comment by Mikaaah** [comment]
Closing it temporarily to prevent abuse

**Comment by Mikaaah** [comment]
Issue at hand does not affect the Server, the editor is purely client side and will Simply save it to the client folder and doesnt edit the server sided skilltree
