### ISSUE TITLE
❰Bug❱ 💾 - Mechanical Saw has no Recipe for Slabs

### ISSUE THREAD

**Issue by NoHandZz1** [Mikaaah/TownsAndKingdoms#104]
**Describe the bug**
<u>Mechanical Saw has no Recipe for Slabs.</u>

►

**To Reproduce**
<u>Open Recipe Page for Oak Slabs:</u>

►

**Expected behavior**
<u>Should be a Recipe to turn Oak Planks into Slabs without using Mechanical Crafters</u>

►

**Screenshots**
<u>![image](https://github.com/user-attachments/assets/7a0ef431-e662-4102-8dd2-0131e74ab086).</u>

►

**Additional context**
<u>Quest even states that i should use more Saws</u>

►

**Comment by Mikaaah** [comment]
Hmm thats odd, it should work fine. Ill check it out tonight.

**Comment by Mikaaah** [comment]
Resolved in Next Update
