### ISSUE TITLE
❰Bug❱ 💾 - No Millstone Recipe for Crushed Copper/Veridium

### ISSUE THREAD

**Issue by The-Nib** [Mikaaah/TownsAndKingdoms#105]
**Describe the bug**
Making copper ore from veridium is impossible early due to crushed copper not having a recipe with a millstone.

►

**To Reproduce**
Click on the recipe for Crushed Copper or the Uses for Veridium

►

**Expected behavior**
Being able to use both the grindstone and the crushing wheel to crush veridium to obtain crushed copper. Also says so in the quest book.

►

**Screenshots**
![image_2024-09-07_053106677](https://github.com/user-attachments/assets/180e61a9-42b3-40c6-ae89-59af1317b9f6)
![image_2024-09-07_053132630](https://github.com/user-attachments/assets/5f13295c-ef44-4705-98ab-78566f81c238)

**Comment by The-Nib** [comment]
After looking more, crushed gold, zinc, iron, redstone, and quartz all have this problem.

**Comment by Mikaaah** [comment]
Ill look into it

**Comment by Mikaaah** [comment]
Resolved in Next Patch
