### ISSUE TITLE
❰Feature❱ 📦 - Dual wield weaponry

### ISSUE THREAD

**Issue by Pokefanatic95** [Mikaaah/TownsAndKingdoms#107]
**Describe the solution you'd like**
the abiltiy to wield a 1 handed weapon in each hand (also for warglaives to be the 1 handed weapons they are mean to and for another sword from simply swords to be a 1 handed one like its supposed to be, a Halberd DEFINITELY isnt a one handed weapon at all, but the warglaives and longswords CAN be)

**Is your feature request related to a problem? Please describe.**
Its hard to enjoy custom weapons and things when you cant wield them in your desired way

**Example // Link**
Having a Warglaive or sword in each hand and being able to attack a little faster when having one in each hand

**Additional context**
i know a modpack that has this with the Simply swords mod (pack is BCG+ w/cobblemon) so it can be done. im just hoping it can happen here too

**Comment by Mikaaah** [comment]
Thats not with epic fight, the weapon styles don't support dual wielding. Longswords will not be dual wielded, war glaives i might look into
