### ISSUE TITLE
❰Feature❱ 📦 - Remove Miniecolonies building creation from Blur

### ISSUE THREAD

**Issue by Demerso** [Mikaaah/TownsAndKingdoms#108]
**Describe the solution you'd like**
It would be nice for the screen not to be blurred when placing a Minecolonies building.

**Is your feature request related to a problem? Please describe.**
Right now, the screen is blurred when using the building tool, which makes it hard to see what you're doing.

**Comment by Demerso** [comment]
You can edit the blur config to add "com.ldtteam" to the exclusion list. This will remove all the UIs from Minecolonies, there might be a way to select only the build tool screen, but I haven't found it. If you want me to look further into it, ping me.

**Comment by Mikaaah** [comment]
Resolved in 3.04h
