### ISSUE TITLE
❰Bug❱ 💾 -  Tin Washing Conflicted/Not Producing Glowstone

### ISSUE THREAD

**Issue by The-Nib** [Mikaaah/TownsAndKingdoms#109]
**Describe the bug**
The recipe for washing crushed tin ore has a conflicting recipe which gives 2 different tin types, and does not give the glowstone byproduct.

►

**To Reproduce**
Wash crushed tin ore

►

**Expected behavior**
Washing Crushed tin ore gives only 1 type of tin nugget and gives the glowstone by-product as advertised.

►

**Screenshots**
![2024-09-12_07 39 19](https://github.com/user-attachments/assets/4c6855a3-e2b3-4147-81b1-5d682026869d)
![2024-09-12_07 49 47](https://github.com/user-attachments/assets/74166bea-4083-48d1-82ff-fd59e61bed0e)

**Comment by Mikaaah** [comment]
Most likely a conflict with the other recipes, will fix it

**Comment by Mikaaah** [comment]
Resolved in 3.04h
