### ISSUE TITLE
❰Bug❱ 💾 - Fluix Dust initial acquirement unintuitive

### ISSUE THREAD

**Issue by The-Nib** [Mikaaah/TownsAndKingdoms#112]
**Describe the bug**
Fluix dust is not able to be initially obtained other than from a ae2 villager which I am not entirely sure if that's intentional or not.

►

**Expected behavior**
For there to be a recipe that is significantly more expensive than the easily automatable recipe, for example requiring a block of certus quartz and a block of redstone for a singular crystal.
►

**Screenshots**
![2024-09-13_12 28 07](https://github.com/user-attachments/assets/9b2b1c8f-0756-4eda-b49a-5877cd0453c7)
![2024-09-13_12 28 01](https://github.com/user-attachments/assets/9557f979-3ba2-44e7-b8a5-91ffb3ab22da)
![2024-09-13_12 28 00](https://github.com/user-attachments/assets/1ab448a3-165a-4910-8bda-2670c3986542)

►

**Additional context**
Apologies for the wording, I could not find out how to better word the problem off the top of my head.

►

**Comment by Mikaaah** [comment]
Resolved in 3.04h
