### ISSUE TITLE
❰Bug❱ 💾 - Quartz Wrenches Consumed by Calculation Mechanism

### ISSUE THREAD

**Issue by The-Nib** [Mikaaah/TownsAndKingdoms#113]
**Describe the bug**
For the logistic chain for the calculation mechanism, when a quartz wrench is deployed by a deployer onto the in-progress mechanism, it is entirely consumed as an item like an andesite alloy for the rotation mechanism.
►

**To Reproduce**
Attempt making a Calculation mechanism through the Recipe Sequence.

►

**Expected behavior**
I expect for the wrench to instead go down in durability like the hammer does in the Rotation Mechanism recipe.

►

**Screenshots**
![2024-09-13_15 08 51](https://github.com/user-attachments/assets/0db05aa4-58dd-496f-a51a-6ad31770d6da)

**Comment by Mikaaah** [comment]
Already Fixed this in the Update Im Currently Working on!

**Comment by Mikaaah** [comment]
Resolved in 3.04h
