### ISSUE TITLE
❰Bug❱ 💾 - Quests aren't being completed

### ISSUE THREAD

**Issue by BruceVayne99** [Mikaaah/TownsAndKingdoms#114]
**Describe the bug**
<u>Progress for quests doesn't update for up to 5 minutes</u>

►

**To Reproduce**
<u>Upon creating/finding an item for a quest, quest doesn't register as being complete immediately and takes a few minutes.</u>

►

**Expected behavior**
<u>Quest should be marked as complete immediately.</u>

►

**Comment by Mikaaah** [comment]
Not a bug, intentional behavior to prevent lagg due to the severe amount of quests. Dropping and Picking up generally resolves it
