### ISSUE TITLE
❰Bug❱ 💾 - Recipe conflict "Andesite Alloy Sheet"

### ISSUE THREAD

**Issue by EndlessGemji** [Mikaaah/TownsAndKingdoms#116]
**Describe the bug**
<u>There are two types of "Andesite Alloy Sheet" with the same recipe they are from the mods "Create: Dreames & Desires" and "Create Deco" but the way they are made you can only get the one from "Create: Dreames & Desires".
The problem is that each of them is needed for different recipes.</u>

►

**To Reproduce**
<u>Place "Andesite Alloy" under a powered "Mechanical Press" to get an "Andesite Alloy Sheet" from the mod "Create: Dreames & Desires".</u>

►

**Expected behavior**
<u>A way to get both types of Sheet or a way to use both types of Sheet in all recipes.</u>

►

**Screenshots**
<u>![grafik](https://github.com/user-attachments/assets/c11ec0af-5131-41d7-b3d3-05ee84f5e2f0) 
![grafik](https://github.com/user-attachments/assets/1399df7b-5736-40c6-a588-c618ce4d49df)

</u>

►

**Additional context**
<u>Not tested but "Zinc Sheet" have according to JEI the same recipe problem. </u>

►

**Comment by Mikaaah** [comment]
Mod was added post recipe development, will replace all deco recipes with the dd sheets

**Comment by Mikaaah** [comment]
Resolved in 3.05
