### ISSUE TITLE
❰Bug❱ 💾 - Player not automatically given access to Overworld

### ISSUE THREAD

**Issue by ReflectionGolden** [Mikaaah/TownsAndKingdoms#117]
<u>In my singleplayer world, I have gone into the Twilight forest and The Nether, only to be unable to return to The Overworld once I attempted to go back through my portals. I had used the /kill command (I am using keep inventory) in order to return, until it occured to me that it could be related to the dimension locking.

So I ran the command "/dimension minecraft:overworld access" and I was able to go back through the portals.

The player does not get automatic access to the overworld, despite spawing there, and this should be changed in some way (however you lock the dimensions, make sure the overworld isn't a part of it).</u>

**Comment by Mikaaah** [comment]
Alright will add the script for it, it should automaticly run but it seems it doesnt

**Comment by Mikaaah** [comment]
Resolved in 3.05
