### ISSUE TITLE
❰Bug❱ 💾 - Not able to access Vendor Blocks in claims

### ISSUE THREAD

**Issue by The-Nib** [Mikaaah/TownsAndKingdoms#118]
**Describe the bug**
Vendor blocks from the Create: Numismatics mod that are in a ftb:claimed chunk are not able to be accessed by players that do not have access to that chunk. Lootr Chests and Paraglider Goddess Statues also have this problem.
►

**To Reproduce**
Have a player place down a vendor in their claimed chunk, configure it, and have a different player attempt to purchase/sell to it.
►

**Expected behavior**
It is expected for a player that does not have ftb chunk access to be able to purchase/sell to the vendor despite not having access to the claim.

►

**Comment by Mikaaah** [comment]
hmm ill look into the issue, might be a setting (hopefully)

**Comment by Mikaaah** [comment]
Seems like adding ftbchunks:interact_whitelist to the tag of the block will resolve the issue, will fix next update.

**Comment by Mikaaah** [comment]
Resolved in 3.05
