### ISSUE TITLE
❰Feature❱ 📦 - 

### ISSUE THREAD

**Issue by Sayikin** [Mikaaah/TownsAndKingdoms#120]
**Describe the solution you'd like**

add leaky 

that mod helps with item leaking and can notify you or the server.

**Is your feature request related to a problem? Please describe.**
farm leaking

**Example // Link**
(https://www.curseforge.com/minecraft/mc-mods/leaky)

**Additional context**

**Comment by Mikaaah** [comment]
Leaky only works properly for those with OP, meaning its just mostly bloat to the server.

**Comment by Sayikin** [comment]
Why should it only work for OP?
It automatically detects farm leaks, reports them publicly or just to OP, and deletes them. No player is involved in this process.

**Comment by Mikaaah** [comment]
Its not being added. It will be only set to operators otherwise since it will simply make players fight one another because they are going to blame them for lagg.
