### ISSUE TITLE
❰Feature❱ 📦 - Better Beginnings, a more immersive early game

### ISSUE THREAD

**Issue by nice-john** [Mikaaah/TownsAndKingdoms#121]
**Describe the solution you'd like**
I would love to feel more immersed in the modpack in the early game. This modpack is so so well done I feel like I'm playing minecraft story mode or something sometimes but when I start a new world its just the same old thing ive done a thousand times, punch tree, make crafting table, then the early game is over. I would have so much more fun if I really felt like I was immersed in this fantasy world by having a mod like Better Beginnings or something. The mod revamps the early game progression in a vanilla friendly way, without being too realistic, grindy, or bloated. It makes copper actually have a use since it is so abundant and pointless without mods, and it slows down the player a little so they arent in full iron on day one. It even makes charcoal useful again since you cant mine coal until you have iron tools which means you have to actually use fuel sources other than coal for the first time since you first played minecraft in 2012. Here's the link: https://www.curseforge.com/minecraft/mc-mods/better-beginnings

**Comment by Mikaaah** [comment]
To much of a change, this is more for a hardcore type modpack. Not planned.
