### ISSUE TITLE
❰Bug❱ 💾 - JER villager trades list doesn't include the trades for the Cartographer

### ISSUE THREAD

**Issue by ReflectionGolden** [Mikaaah/TownsAndKingdoms#122]
**Describe the bug**
<u>I'm doing some villager trades and wanted to see everything that the cartographer could trade now, but they don't seem to be in the list (although many other villagers are).</u>

►

**To Reproduce**
<u>press use on an item that can be traded, and go to the "Villager Trades" tab before clicking on the tab name to see all villager trades.
Then, scroll through the different pages in that tab keeping an eye on the "points of interest" slot, and see that none of them show the cartography table.</u>

►

**Expected behavior**
<u>There should be ab page that shows the cartographer and what trades they are capable of offering.</u>

►

**Comment by Mikaaah** [comment]
Sadly this is an issue with jer and needs to be resolved with the mod itself
