### ISSUE TITLE
❰Bug❱ 💾 - eu corrupted chunks

### ISSUE THREAD

**Issue by EndlessGemji** [Mikaaah/TownsAndKingdoms#123]
**Describe the bug**
<u>chunk -60 -1118 x -62 -1120 area fails to load might be something there that breaks them.
bug was posted in case that this is from an block/entity and might happen in other areas too.</u>

►

**To Reproduce**
<u></u>

►

**Expected behavior**
<u></u>

►

**Screenshots**
<u></u>

►

**Additional context**
<u></u>

►

**Comment by Mikaaah** [comment]
Chunks are not corrupted, they are not loading due to tps issues. Once automatic restart kicks in it will work again.

Corruption on servers will instantly crash them :D

**Comment by EndlessGemji** [comment]
it didnt seemed like the server was lagging then, i will check the area after restart just to be sure.
