### ISSUE TITLE
Cant find server files

### ISSUE THREAD

**Issue by tanwashere** [Mikaaah/TownsAndKingdoms#13]
Ive looked on curse forge website and technic web sight and cant find the server files. i want to make a server using this pack for me and a few friends of mine.

**Comment by Mikaaah** [comment]
Im working on them! They will be there in about a few hours!

**Comment by Mikaaah** [comment]
Version 1.02 Has been Released - It comes with Serverfiles, Curse is currently progressing the files as for technic they are up!
