### ISSUE TITLE
❰Feature❱ 📦 - Make Builder's Goggles a curio

### ISSUE THREAD

**Issue by ReflectionGolden** [Mikaaah/TownsAndKingdoms#130]
**Describe the solution you'd like**
The builder's Goggles for Minecolonies should be a curio so that the player doesn't have to remove their helmet when viewing in progress buildings.

**Is your feature request related to a problem? Please describe.**
When I want to view my buildings in progress, I have to switch between my helmet and my builder's goggles, which while easy by using the right click functionality to swap between them, I would like to potentially make use of both at the same time.

**Example // Link**
You could make it a mask or some kind of charm to be useable in the Curios slots.

**Comment by Mikaaah** [comment]
The code requires it to be a helmet slot ive attempted it it will not work

**Comment by ReflectionGolden** [comment]
That’s quite unfortunate. Oh well, at least I know you’ve tried.
