### ISSUE TITLE
❰Bug❱ 💾 - EU-server restart plugin timer broke

### ISSUE THREAD

**Issue by EndlessGemji** [Mikaaah/TownsAndKingdoms#131]
**Describe the bug**
restart at 06.10.2024 13:00 (GMT +2), countdown started 24 min late and took 77min to do so with each countdown message 10 times repeating to a total of 60 messages, after it finally restarted it did it 2 times in a row.
►

**To Reproduce**
will be seen in around 4 hours

►

**Expected behavior**

►

**Screenshots**

►

**Additional context**

►

**Comment by Mikaaah** [comment]
Its not a bug, connection issue with host broke

**Comment by EndlessGemji** [comment]
problem repeats at the same time +17min on the next day not sure if its a rnd connection problem.

oh and sry i just notest that this is for the mod itself and not the official servers.
just didnt know where to write it.
