### ISSUE TITLE
❰Bug❱ 💾 - Cast Iron Ingot (Create: TFMG)

### ISSUE THREAD

**Issue by SirLiyanx** [Mikaaah/TownsAndKingdoms#132]
**Describe the bug**
<u>A clear and concise description of what the bug is.</u>

► Can't craft it using mixer you get Samurai Dynasty Steel Ingot instead.

**To Reproduce**
<u>Steps to reproduce the behavior:</u>

► Setup Mixer with heated Blaze Burner input iron and coal 1:1 ratio.

**Expected behavior**
<u>A clear and concise description of what you expected to happen.</u>

► Get out Cast Iron Ingot, since you can get the Samurai Dynasty Steel Ingot in other ways.

**Screenshots**
<u>If applicable, add screenshots to help explain your problem.</u>

►

**Additional context**
<u>Add any other context about the problem here.</u>

►

**Comment by SirLiyanx** [comment]
After restarting the Server i had running it now outputs Cast Iron. I changed nothing. If possible i think it would be better to still remove the Samurai Dynasty Steel from the Mixer as a Recipe since it overlaps

**Comment by Mikaaah** [comment]
The recipe is overwritten, most likely an issue with the scripts not loading.
