### ISSUE TITLE
❰Bug❱ 💾 - soulbound enchant broke

### ISSUE THREAD

**Issue by EndlessGemji** [Mikaaah/TownsAndKingdoms#133]
**Describe the bug**
on the EU-server, on my last death all items that had the soulbound enchant just vanished.
►

**To Reproduce**
die with soulbound items equiped. (didnt test it myself, had as far as i know no other gear that i could just sacrifice for a test) 
►

**Expected behavior**
the soulbound enchanted items should land in my inventory when i resurect.

►

**Screenshots**

►

**Additional context**

►

**Comment by Mikaaah** [comment]
Did you have the twilight charm in your inventory? Or did the items have curse of vanishing?

**Comment by EndlessGemji** [comment]
if its something that goes in the charm slot then no and as far as i know i didnt had any curses on the gear end even if i lost my backpack too and this one i know i got all the time back when i died.

**Comment by EndlessGemji** [comment]
the death message i got them was strange too i never saw "was drained by a corrupted enchantment" before

**Comment by Mikaaah** [comment]
Oh do you have like lifemending

**Comment by EndlessGemji** [comment]
i think this one was it on it but i dont know how this would cause it so that i get onehitted and all items with soulbound dont spawn in my inventory after i resurect

**Comment by Mikaaah** [comment]
EU server correct? I wont be able to join for a day or two but will return the items once im back

**Comment by EndlessGemji** [comment]
yes EU server, thank you. would this be only blanks or or do you have access to the exact gear i lost(the backpack contents are to many to remember.

**Comment by EndlessGemji** [comment]
ashk just told me that it was not live-mending only mending

**Comment by Mikaaah** [comment]
Ive got access to all the gear as its registered into the death history

**Comment by EndlessGemji** [comment]
ok, if im not on you can give it Ashkshel too.
