### ISSUE TITLE
❰Bug❱ 💾 - singleplayer won't start version 3.05

### ISSUE THREAD

**Issue by wilkuv** [Mikaaah/TownsAndKingdoms#137]
when I try to run singleplayer it doesn't start and gets stuck on the world creation screen
[latest.log](https://github.com/user-attachments/files/18049263/latest.log)
here is the logs

**Comment by sebkuip** [comment]
For support, please use our discord server. The GitHub issues are mostly for proper bug reports or things that affect multiple people.
