### ISSUE TITLE
Contenttweaker missing items

### ISSUE THREAD

**Issue by mdex034** [Mikaaah/TownsAndKingdoms#18]
![Towns   Kingdoms 2_8_2023 2_21_13 PM](https://user-images.githubusercontent.com/124826460/217642460-a2911046-8031-4031-a1b5-dc95cbebe865.png)

I am using ATLauncher and modpack version is 1.04

**Comment by Mikaaah** [comment]
Hello,

Make sure the ATLauncher is downloading the script folder aswell
Its required to run the pack, Since neither technic or curse have this issue it is most likely related due to using an external launcher

**Comment by mdex034** [comment]
How do I download and install the script folder since ATLauncher isn't installing it, I tried reinstalling it.

**Comment by Mikaaah** [comment]
Download the Curseforge Zip, Extract it, go into overrides, and copy everything. Then open the modpack on atlauncher go to the folder of it and then paste everything in there.

**Comment by mdex034** [comment]
Thanks this worked, though it is weird ATLauncher didn't install correctly since it already had the folders and some files in the modpack folder.

**Comment by Mikaaah** [comment]
Closing Issue - Resolved
