### ISSUE TITLE
Adamantite don't spawn in End

### ISSUE THREAD

**Issue by Subawuu** [Mikaaah/TownsAndKingdoms#35]
I tried to find Adamantite in Single-and Multiplayer and searched for hours but there is none. You basically can't find it.

**Comment by Mikaaah** [comment]
It spawns in extreme amounts in the end, it spawns within the small red grassed islands in the end :D

**Comment by Mikaaah** [comment]
The "Shattered Viscal Islands" Biome

**Comment by Subawuu** [comment]
> It spawns in extreme amounts in the end, it spawns within the small red grassed islands in the end :D

That is Ametrine not Adamantite :p. Adamantite has unbreakable tools and should spawn under the end islands but it don't.

**Comment by Subawuu** [comment]
Its from the Mod Elightened End. There is a block -Eduring Waste- when you smelt that you get Adamantite. This block is not spawning.
