### ISSUE TITLE
[BUG]Using the un-redo menu button in a supply camp menu crashes the game

### ISSUE THREAD

**Issue by sebkuip** [Mikaaah/TownsAndKingdoms#49]
[crash-2023-04-18_22.26.39-client.txt](https://github.com/Mikaaah/TownsAndKingdoms/files/11266113/crash-2023-04-18_22.26.39-client.txt)
![image](https://user-images.githubusercontent.com/61157793/232898672-6ef231d3-456c-4485-b7a0-098d73b324ff.png)

**Comment by Mikaaah** [comment]
Should be resolved in 2.04/Can't Replicate anymore.
