### ISSUE TITLE
Crash Issue with Blueprints.

### ISSUE THREAD

**Issue by Mikaaah** [Mikaaah/TownsAndKingdoms#65]
Most likely caused by VBO Rendering from Immersive.

**Comment by Mikaaah** [comment]
Cant fix - Awaiting Immersive Engineering.

**Comment by AMT19** [comment]
Issue still up as of now

**Comment by Mikaaah** [comment]
Caused on Immersives end, unable to patch myself

**Comment by Mikaaah** [comment]
Removed cause of blueprint crash in 3.0
