### ISSUE TITLE
It is impossible to craft the angel ring in survival

### ISSUE THREAD

**Issue by sebkuip** [Mikaaah/TownsAndKingdoms#72]
The angel ring recipe requires a flugel tiara. When crafted in survival in a crafting table, the flugel tiara has special NBT data making it incompatible with the angel ring recipe. A creative spawned flugel tiara works fine. The tag in question is the `{variant: 0}` tag.
creative spawned:
![creative spawned](https://user-images.githubusercontent.com/61157793/236283497-00fb770b-5c23-49c6-97a8-fcdfb91510f5.png)
crafted:
![crafted](https://user-images.githubusercontent.com/61157793/236283553-1dba3406-7ac3-4bc2-8868-c470ce0a584c.png)

**Comment by Mikaaah** [comment]
Recipe Changed/Reworked - Next Update
