### ISSUE TITLE
server not finding user_jvr_arg.txt

### ISSUE THREAD

**Issue by AMT19** [Mikaaah/TownsAndKingdoms#73]
Hello, I tried setting up a server, but whaterver I did, nothing worked. The server ran fine until it tries to load the java arguments at which point it returns : impossible to find or load the principal class @user_jvm_args.txt
The file is present in the folder and it contains my -Xmax6G argument

![image](https://user-images.githubusercontent.com/132953463/236940030-3c7898f6-52e3-48aa-b0c8-50252c6a78ce.png)

**Comment by Mikaaah** [comment]
Update your Java to Java 17, Minecraft 1.17/1.18 runs on Java 17 and not Java 8!

**Comment by AMT19** [comment]
thanks
