### ISSUE TITLE
Bulk blasting soul sand has 3 conflicting recipes

### ISSUE THREAD

**Issue by sebkuip** [Mikaaah/TownsAndKingdoms#74]
It makes soul glass, soul stone and scoria.
![image](https://user-images.githubusercontent.com/61157793/236940027-4c01fb6f-2437-4e57-aac2-890aa9742fb8.png)
Scoria should probably be the only intended outcome of this recipe.

**Comment by Mikaaah** [comment]
Fixed in next Update - Soulstone & Soulglass now have alternative recipes.
