### ISSUE TITLE
Cannot make Empty goblet 

### ISSUE THREAD

**Issue by BledekJakub** [Mikaaah/TownsAndKingdoms#86]
Can't make "Empty Goblet" from Knight Quest, the recipe is shared with "Copper Can" from Tinkers'. Crafting table doesn't give option to change item being crafted.

**Comment by Mikaaah** [comment]
Use a different crafting table, somehow the vanilla table does not support the recipe swapping right now.

**Comment by BledekJakub** [comment]
Yep that works sorry for late reply, completely forgot about this.

**Comment by Mikaaah** [comment]
Issue Patched in 3.0 // Not yet Released but patched.
