### ISSUE TITLE
End Dimension Crashes the Game

### ISSUE THREAD

**Issue by MidnightMod** [Mikaaah/TownsAndKingdoms#92]
Hey so my IGN and Discord are both MidnightMod. I'm pretty active on the discord and the US Server. I recently went into the End but when I do that crashes the game. Im not sure if that is a dimensional thing (It probably shouldn't since im able to access like 3 other dimensions) but I cannot join back and then when I do I crash the server for other players and that's complicated. I'm wondering if I could be teleported into Overworld OR if the End could be reset/ fixed (reloaded or something).

**Comment by sebkuip** [comment]
This GitHub is for the modpack itself. Use the discord server for help with the official servers.
