### ISSUE TITLE
CTD from tinker tools made of soul stained steel

### ISSUE THREAD

**Issue by notjac0b** [Mikaaah/TownsAndKingdoms#94]
easy to replicate, make a tinker weapon or spawn one in that has soul stained steel from malum as a blade. instant ctd. I'd recommend disabling the parts until you fix this since it can hard lock a singleplayer world as it will just crash every time you load it if the item is in your inventory.

The game crashed whilst ticking player
Error: java.lang.NoClassDefFoundError: com/sammy/malum/core/setup/content/AttributeRegistry

crash log
https://pastebin.com/wjSZDdNL

**Comment by Mikaaah** [comment]
Issue related to current version, not present in upcoming 3.0 update.

Will be resolved :D
